---
- name: add/remove administrative users
  user:
    name: "{{ item.username }}"
    groups: wheel
    remove: true
    state: "{{ item.state }}"
  with_items: admin_users

- name: add administrative users' SSH keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'authorized_keys/' + item.username + '.keys') }}"
  with_items: admin_users
  # only operate on present users; absent users don't have a homedir in /etc/passwd anymore
  when: item.state == 'present'

- name: add service account
  user:
    name: "{{ service_account }}"
    comment: Buildbot Service Account
    state: present
    groups: wheel
