# elk networking configuration
---
kibana_port: 5602
elastic_port: 9100
logstash_port: 8080
oauth2_proxy_port: 8081
elastic_configuration: /usr/local/etc/elasticsearch/elasticsearch.yml
logstash_configuration: /usr/local/etc/logstash/logstash.conf
kibana_configuration: /usr/local/etc/kibana.yml
oauth2_proxy_configuration: /usr/local/etc/oauth2_proxy.conf
